#!/usr/bin/perl -w
# [0day (xc) Our] 
# http://0dev.us.to

#### Check whether user is root or not if not die

my $whoami;
chomp ($whoami = `whoami`);
die "You need to be root to run this program" unless $whoami eq "root";

## Setting up systemd Script 
open FILE , ">" , "/etc/systemd/system/iptables-on.service";
print FILE '
[Unit]
After=network.service

[Service]
ExecStart=/etc/init.d/iptables-on

[Install]
WantedBy=default.target
';
close FILE;


#### Setting up firewall log file in /var/log/kern.log
open FILE, ">", "/etc/iptables-rules" or die "$!";
print FILE '
# Generated by iptables-save v1.3.1 on Sun Apr 23 05:32:09 2006
*filter
:INPUT ACCEPT [273:55355]
:FORWARD ACCEPT [0:0]
:LOGNDROP - [0:0]
:OUTPUT ACCEPT [92376:20668252]
-A INPUT -m conntrack -ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -j LOGNDROP
-A LOGNDROP -p tcp -m limit -limit 5/min -j LOG -log-prefix "Denied TCP: " -log-level 7
-A LOGNDROP -p udp -m limit -limit 5/min -j LOG -log-prefix "Denied UDP: " -log-level 7
-A LOGNDROP -p icmp -m limit -limit 5/min -j LOG -log-prefix "Denied ICMP: " -log-level 7
-A LOGNDROP -j DROP
COMMIT
# Completed on Sun Apr 23 05:32:09 2006
';
close FILE;

#### iptables-restore Make the rule working
system "iptables -F";
open FILE , ">" , "/etc/init.d/iptables-on";
print FILE '
#! /bin/sh
### BEGIN INIT INFO
# Provides: scriptname
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start daemon at boot time
# Description: Enable service provided by daemon.
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /lib/lsb/init-functions

# Carry out specific functions when asked to by the system
case "$1″ in
start)
/sbin/iptables -F
/sbin/iptables-restore < /etc/iptables-rules
;;
restart|reload|force-reload)
/sbin/iptables -F
/sbin/iptables-restore < /etc/iptables-rules
;;
stop)
/sbin/iptables -F
;;
*)
echo "Usage: /etc/init.d/iptables-on {start|stop}"
exit 1
;;
esac

exit 0
';
close FILE;

#### Make iptables-on by default
system "chmod +x /etc/init.d/iptables-on";
system "/etc/init.d/iptables-on restart";
